### ISSUE TITLE
Hardcoded API Key

### ISSUE THREAD

**Issue by carolynrehm** [Finance-Portfolio-Manager/portfolio_manager_frontend#9]
https://github.com/Finance-Portfolio-Manager/portfolio_manager_frontend/blob/ca873da17674d98048288572ec4d30bc9a378bf1/src/components/chart-component/chart-component.js#L26

[see backend issue](https://github.com/Finance-Portfolio-Manager/API/issues/3)

**Comment by Sife-ops** [comment]
Moved API key to .env until I get it working with our own API.
